# -*- coding: utf-8 -*-
"""smart-poverty-forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1asGO3QrZCRWrnkZ7hXIgukUPbog42MKx
"""

import pandas as pd
import glob

files = glob.glob("SAIPE_full_dataset_2005_2023*.csv")
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

# Display available columns to identify the correct names
print("Available columns:", df.columns.tolist())

# Once correct columns are identified, uncomment and modify the selection below
df = df[[
    "state", "county", "year",
    "median_household_income",
    "poverty_all",
    "poverty_under_17"
]]

# Check missing values
# df.isna().sum()

# Forward fill missing values
# df = df.fillna(method="ffill")
display(df.head())

# Lag features
df["poverty_all_last_year"] = df.groupby("county")["poverty_all"].shift(1)
df["poverty_under18_last_year"] = df.groupby("county")["poverty_under_17"].shift(1)
df["income_last_year"] = df.groupby("county")["median_household_income"].shift(1)

# Rolling 3-year average
df["poverty_all_3yr_avg"] = df.groupby("county")["poverty_all"].rolling(3).mean().reset_index(0, drop=True)
df["poverty_under18_3yr_avg"] = df.groupby("county")["poverty_under_17"].rolling(3).mean().reset_index(0, drop=True)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import joblib
import os

# Drop rows with NaN values created by lag/rolling features
df_cleaned = df.dropna()

# Features & targets
features = ["median_household_income", "poverty_all_last_year", "income_last_year", "poverty_all_3yr_avg"]
X = df_cleaned[features]
y_all = df_cleaned["poverty_all"]
y_under18 = df_cleaned["poverty_under_17"]

# Split
X_train, X_test, y_train_all, y_test_all = train_test_split(X, y_all, test_size=0.2, random_state=42)
X_train, X_test, y_train_under18, y_test_under18 = train_test_split(X, y_under18, test_size=0.2, random_state=42)

# Train models
model_all = RandomForestRegressor(n_estimators=300, random_state=42)
model_all.fit(X_train, y_train_all)

model_under18 = RandomForestRegressor(n_estimators=300, random_state=42)
model_under18.fit(X_train, y_train_under18)

# Create the 'backend' directory if it doesn't exist
os.makedirs("../backend", exist_ok=True)

# Save models
joblib.dump(model_all, "../backend/poverty_all_model.pkl")
joblib.dump(model_under18, "../backend/poverty_under18_model.pkl")

from google.colab import files

files.download('../backend/poverty_all_model.pkl')
files.download('../backend/poverty_under18_model.pkl')

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred_all = model_all.predict(X_test)
print("MAE:", mean_absolute_error(y_test_all, y_pred_all))
print("RMSE:", np.sqrt(mean_squared_error(y_test_all, y_pred_all)))
print("R2:", r2_score(y_test_all, y_pred_all))